import httpx


OLLAMA_URL = "http://localhost:11434/api/generate"
OLLAMA_MODEL = "llama3.1"


def build_prompt(code: str, findings: list[dict], instruction: str | None) -> str:
    finding_summary = "\n".join(
        [f"- {f.get('check_id', 'unknown')}: {f.get('extra', {}).get('message', '')}" for f in findings]
    )
    return (
        "You are a secure coding assistant.\n"
        "Fix the vulnerabilities and keep behavior unchanged when possible.\n"
        f"User instruction: {instruction or 'N/A'}\n"
        f"Findings:\n{finding_summary}\n\n"
        f"Code:\n{code}\n\n"
        "Return only fixed code, no markdown fences."
    )


async def generate_fix(code: str, findings: list[dict], instruction: str | None) -> tuple[str, str]:
    prompt = build_prompt(code, findings, instruction)
    payload = {
        "model": OLLAMA_MODEL,
        "prompt": prompt,
        "stream": False,
    }

    async with httpx.AsyncClient(timeout=45.0) as client:
        resp = await client.post(OLLAMA_URL, json=payload)
        resp.raise_for_status()
        data = resp.json()

    fixed_code = data.get("response", "").strip()
    explanation = "Generated by local LLM based on Semgrep findings."
    return fixed_code, explanation
